-- MySQL Script generated by MySQL Workbench
-- Thu Oct 14 23:00:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gh` DEFAULT CHARACTER SET utf8 ;
USE `gh` ;

-- -----------------------------------------------------
-- Table `gh`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gh`.`Prestamo` (
  `idprestamo` INT NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFinal` DATE NOT NULL,
  `Horainicio` VARCHAR(45) NOT NULL,
  `Horafinal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprestamo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gh`.`Mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gh`.`Mantenimiento` (
  `idmantenimiento` INT NOT NULL,
  `Fechamantenimineto` DATE NOT NULL,
  `Entrega` DATE NOT NULL,
  `devolucion` DATE NOT NULL,
  PRIMARY KEY (`idmantenimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gh`.`Devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gh`.`Devolucion` (
  `devolucion` INT NOT NULL,
  `fechaentrega` VARCHAR(45) NOT NULL,
  `fechaprestamo` VARCHAR(45) NOT NULL,
  `fechadevolucion` VARCHAR(45) NOT NULL,
  `Horaentrega` VARCHAR(45) NOT NULL,
  `horadevolucion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`devolucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gh`.`Equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gh`.`Equipos` (
  `sn` INT NOT NULL,
  `ct` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `Entrega_id` INT NOT NULL,
  `Mantenimiento_idmantenimiento` INT NOT NULL,
  `Devolucion_devolucion` INT NOT NULL,
  PRIMARY KEY (`sn`, `Entrega_id`, `Mantenimiento_idmantenimiento`, `Devolucion_devolucion`),
  INDEX `fk_Equipos_Entrega1_idx` (`Entrega_id` ASC),
  INDEX `fk_Equipos_Mantenimiento1_idx` (`Mantenimiento_idmantenimiento` ASC),
  INDEX `fk_Equipos_Devolucion1_idx` (`Devolucion_devolucion` ASC),
  CONSTRAINT `fk_Equipos_Entrega1`
    FOREIGN KEY (`Entrega_id`)
    REFERENCES `gh`.`Prestamo` (`idprestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_Mantenimiento1`
    FOREIGN KEY (`Mantenimiento_idmantenimiento`)
    REFERENCES `gh`.`Mantenimiento` (`idmantenimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_Devolucion1`
    FOREIGN KEY (`Devolucion_devolucion`)
    REFERENCES `gh`.`Devolucion` (`devolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gh`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gh`.`administrador` (
  `idlogin` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gh`.`tipo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gh`.`tipo_Usuario` (
  `usuario` INT NOT NULL,
  `nombreUsario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gh`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gh`.`usuario` (
  `idDocente` INT NOT NULL,
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `facultad` VARCHAR(45) NOT NULL,
  `tel` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `tipo_Usuario_usuario` INT NOT NULL,
  PRIMARY KEY (`idDocente`, `tipo_Usuario_usuario`),
  INDEX `fk_usuario_tipo_Usuario1_idx` (`tipo_Usuario_usuario` ASC),
  CONSTRAINT `fk_usuario_tipo_Usuario1`
    FOREIGN KEY (`tipo_Usuario_usuario`)
    REFERENCES `gh`.`tipo_Usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gh`.`usuario_has_Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gh`.`usuario_has_Prestamo` (
  `usuario_idDocente` INT NOT NULL,
  `usuario_tipo_Usuario_usuario` INT NOT NULL,
  `Prestamo_idprestamo` INT NOT NULL,
  PRIMARY KEY (`usuario_idDocente`, `usuario_tipo_Usuario_usuario`, `Prestamo_idprestamo`),
  INDEX `fk_usuario_has_Prestamo_Prestamo1_idx` (`Prestamo_idprestamo` ASC),
  INDEX `fk_usuario_has_Prestamo_usuario1_idx` (`usuario_idDocente` ASC, `usuario_tipo_Usuario_usuario` ASC),
  CONSTRAINT `fk_usuario_has_Prestamo_usuario1`
    FOREIGN KEY (`usuario_idDocente` , `usuario_tipo_Usuario_usuario`)
    REFERENCES `gh`.`usuario` (`idDocente` , `tipo_Usuario_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_Prestamo_Prestamo1`
    FOREIGN KEY (`Prestamo_idprestamo`)
    REFERENCES `gh`.`Prestamo` (`idprestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gh`.`usuario_has_Devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gh`.`usuario_has_Devolucion` (
  `usuario_idDocente` INT NOT NULL,
  `usuario_tipo_Usuario_usuario` INT NOT NULL,
  `Devolucion_devolucion` INT NOT NULL,
  PRIMARY KEY (`usuario_idDocente`, `usuario_tipo_Usuario_usuario`, `Devolucion_devolucion`),
  INDEX `fk_usuario_has_Devolucion_Devolucion1_idx` (`Devolucion_devolucion` ASC),
  INDEX `fk_usuario_has_Devolucion_usuario1_idx` (`usuario_idDocente` ASC, `usuario_tipo_Usuario_usuario` ASC),
  CONSTRAINT `fk_usuario_has_Devolucion_usuario1`
    FOREIGN KEY (`usuario_idDocente` , `usuario_tipo_Usuario_usuario`)
    REFERENCES `gh`.`usuario` (`idDocente` , `tipo_Usuario_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_Devolucion_Devolucion1`
    FOREIGN KEY (`Devolucion_devolucion`)
    REFERENCES `gh`.`Devolucion` (`devolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
